+ strace -f -e trace=network -c python ../tasks//python/grpc/server.py
strace: Process 9941 attached
strace: Process 9942 attached
strace: Process 9943 attached
E0518 16:44:45.073013676    9933 server_chttp2.cc:40]        {"created":"@1526651085.072885345","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1526651085.072836881","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":345,"referenced_errors":[{"created":"@1526651085.072352784","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1526651085.072279075","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1526651085.072806518","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1526651085.072741833","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}]}
strace: Process 9944 attached
