Traceback (most recent call last):
  File "GitHub/Rest_and_RPC_research/tasks/python/grpc/client.py", line 34, in <module>
    run()
  File "GitHub/Rest_and_RPC_research/tasks/python/grpc/client.py", line 29, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'+str(x)))
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1550214115.454200849","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2636,"referenced_errors":[{"created":"@1550214115.454125745","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1550214115.454051057","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1550214115.454003922","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":202,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:195.251.251.27:8080"}]}]}]}"
>

real	0m1.424s
user	0m1.361s
sys	0m0.060s
